# Bylaws

## Section 1: Name

The incorporated name of this body shall be "Evangel Presbytery, Inc."

## Section 2: Object

The object of this body is to fulfill the requirements for the Presbytery as set forth in the *Book of Church Order of Evangel Presbytery* ([15.8](https://bco.evangelpresbytery.com/form-of-government.html#the-presbytery); hereafter, “ *Book of Church Order” or “BCO”* ). The doctrinal and governmental standards of this Presbytery shall be those stated in the *Book of Church Order* ([Preface, C](https://bco.evangelpresbytery.com/preface.html)). These Bylaws are not to conflict with the *Book of Church Order* , and in any case of conflict, the standards of the *Book of Church Order* shall take precedence.

## Section 3: Members

Members of this Presbytery shall be in two classes: Ordained Ministers of the Word (Pastors) and the particular churches. Standards for examination for membership of both Ministers and churches shall be as set forth in the *Book of Church Order*. Representation of elders from particular churches shall be in accordance with the provisions of the *Book of Church Order*.

## Section 4: Officers

All officers shall be elected by a majority of the votes cast at the Stated Meeting scheduled for that purpose. The various offices of the Presbytery, and their functions, are as follows:

A.  Moderator
    1. Eligibility: The Moderator shall be a Pastor who is a member in good standing of the Presbytery, or an Elder in good standing of a member church of the Presbytery. The Elder does not have to be currently active on the Session of his church if that church follows a rotation system for its Session. A moderator may not succeed himself, nor serve a second term in office within one year of previously having served.
    2. Tenure: The Moderator of the Presbytery shall be chosen at each stated meeting or for a period of time up to one (1) year ([*BCO* 12.3](https://bco.evangelpresbytery.com/form-of-government.html#church-courtsin-general)). He will continue to serve in office until a successor is elected at a Stated Meeting. He will preside over called or other special meetings, and otherwise function as Moderator during his tenure. As a general rule, the position of Moderator should alternate between Pastors and Elders.
    3. Moderator-in-Nomination: At each Stated Meeting of Presbytery or at the Stated Meeting preceding the final meeting of the current Moderator’s tenure, a Moderator-in-Nomination will be elected, with the understanding that his name will automatically be placed in nomination for the office of moderator at the next Stated Meeting. This policy is established to enable men to prepare themselves to function in this office to the best of their ability, and to be aware of current issues before the court. However, election as Moderator-in-Nomination does not require the Presbytery to elect this nominee at its next Stated Meeting, at which time a normal process of nominations and elections will be followed.
    4. Duties:
        a. The Moderator of Presbytery will function as chairman of all meetings of Presbytery, following approved parliamentary procedure.
        b. If no worship service has been held prior to the meeting of Presbytery, the retiring Moderator shall ordinarily bring a message from God's Word in an appropriate time of devotion.
        c. Between meetings, the Moderator has the responsibility to speak for the Presbytery in matters in which the Presbytery itself has made its commitments clear, and he should be consulted in all matters affecting the Presbytery as a whole.
        d. He may appoint a Parliamentarian to serve for each Stated Meeting.
        e. In any emergency the Moderator may, by adequate and appropriate means, including circular letter, telephone notification, or email, change the time or place (or both) of meetings to which the court stands adjourned, giving reasonable notice of such change.
        f. The Moderator shall appoint the members of Temporary Committees and Ad Interim Committees. The Moderator may appoint the chairmen of these committees or he may advise their members to elect chairmen from among themselves. The presbytery is to be informed once committee chairmen have been established.
        g. The Moderator, by the authority vested in him, is an ex-officio member of the Administrative Committee.
B.  Vice Moderator

    The Vice Moderator shall be the immediate past Moderator and shall serve at the request of the Moderator, or when the Moderator is unable to serve. In the event the Vice Moderator is not able to serve, the Stated Clerk shall preside, and, as its first order of business, Presbytery shall nominate and elect a Moderator Pro Tem to moderate during the Moderator’s and Vice Moderator’s absence. The Vice Moderator, by the authority vested in him, is an ex-officio member of the Administrative Committee.
C.  Stated Clerk
    1. Eligibility: The Stated Clerk shall be a Pastor who is a member in good standing of the Presbytery, or an Elder in good standing of a member church of the Presbytery. The Elder does not have to be currently active on the Session of his church if that church follows a rotation system for its Session.
    2. Tenure: The Stated Clerk will be elected at the Spring/Summer Stated Meeting and shall serve for a period of three (3) years. He may succeed himself as often as the Presbytery so desires. It is deemed advisable that this be done whenever possible.
    3. Duties: The Stated Clerk shall perform the duties assigned by the *Book of Church Order* ([12.4](https://bco.evangelpresbytery.com/form-of-government.html#church-courtsin-general)). He shall perform other duties as assigned by the Presbytery. The Stated Clerk may receive an annual stipend to be fixed by the Presbytery. In the administration of his duties, the Stated Clerk shall be under the supervision of the Administrative Committee. The Presbytery shall provide or reimburse the Stated Clerk for all costs required by the duties of his office upon presentation of proper cost statements subject to the limitations of the current approved budget. His duties will include, but not be limited to the following,
        a. keep proper minutes of all Presbytery and Committee/Commission meetings, giving certified extracts therefrom when required;
        b. assemble the items of business to come before the Presbytery and refer each item to the proper committee (if the clerk has questions regarding reference, he is to consult with the Administrative Committee before making reference);
        c. send to each member and church (including men under care) notice of all meetings; note the attendance at each meeting and make recommendations concerning absences at Stated Meetings;
        d. maintain permanent, orderly records of all Presbytery correspondence and other matters;
        e. notify each Committee and Commission chairman of his appointment, membership and business before it;
        f. maintain a supply of necessary forms for use by churches;
        g. make all communications authorized by Presbytery;
        h. open meetings of Presbytery when the Moderator is unable to do so, and serve until a new Moderator is elected;
        i. advise the Moderator in every possible way, by keeping him informed of matters requiring his attention, giving notice for him of Called Meetings of Presbytery or changes in time and place of Meetings, making the facilities of the office available to him for correspondence or other matters, and rendering any service requested by the Moderator in connection with the operation of Presbytery.
        j. He shall be an ex-officio member of Presbytery's Administrative Committee.
    4. Assistant Clerks and Office Staff. When necessary to the performance of his duties, and upon recommendation by the Administrative Committee, the Presbytery may authorize the hiring of clerical help and services (such as printing and duplication) to assist the Stated Clerk in carrying out the duties of his office.
D.  Recording Clerk

    The Recording Clerk shall be appointed by the Stated Clerk for a term of one (1) year, informing the Presbytery of this appointment during his clerk’s report at the beginning of the first presbytery meeting following that appointment. The Recording Clerk shall normally be a member of Presbytery or a ruling elder of a member church. The appointment shall normally be announced at the Spring/Summer Stated Meeting, with term of office to begin at the Fall Stated Meeting. The Recording Clerk may receive a stipend to be fixed by the Presbytery. He shall be given two (2) copies of all committee reports as presented to Presbytery for inclusion in the Minutes and a written copy of all motions adopted by Presbytery. As soon as practicable, he shall convey the Minutes in type-written form (or any other form acceptable to the Stated Clerk), properly recorded, to the Stated Clerk for editing and publishing. The Minutes shall be reviewed by the Stated Clerk and Moderator prior to circulation to the presbytery for their review and approval.
E.  Treasurer
    1. Eligibility: Eligibility for the office of Treasurer shall be the same as for the office of Stated Clerk. The Stated Clerk may also serve as Treasurer.
    2. Tenure: Tenure for the office of Treasurer shall be the same as for the office of Stated Clerk.
    3. Duties: The Treasurer shall perform those duties required of him by the *Book of Church Order* and those other duties as may be assigned by the Presbytery. In the performance of his duties, the Treasurer shall come under the oversight of the Administrative Committee. The Presbytery shall provide or reimburse the Treasurer for all costs required by the duties of his office upon presentation of proper cost statements subject to the limitations of the current approved budget. He shall be bonded in an amount to be determined by the Presbytery, or the books of the presbytery shall be audited, annually. His duties shall include but not be limited to:
        a. custody of the funds and securities belonging to the Presbytery, and not otherwise designated;
        b. receive, deposit, and disburse such funds as directed by the Presbytery;
        c. keep an accurate account of the finances of the Presbytery, not only of those funds in the custody, but also by means of quarterly reports from other committees handling separate funds;
        d. prepare or have prepared reports of the financial condition of the Presbytery at each stated meeting;
        e. in general, perform all of the duties incident to the office of Treasurer.
F.  Trustees
    1. Eligibility: The Board of Trustees of the Presbytery shall consist of the Stated Clerk, plus two other members of Presbytery elected at large. Eligibility for this office shall be the same as for all other offices.
    2. Tenure: Trustees will serve for the period of their Committee Chairmanship, or three (3) years, whichever is shorter. Trustees may be re-elected to office upon two-thirds (2/3)of the votes cast. Election will be held at Spring/Summer Stated Meeting.
    3. Duties: The Trustees shall receive and hold for use of Presbytery all real and personal property, grants, endowments, and such other funds acquired, devised, purchased, or donated, not otherwise disposed of. They shall be the legal Officers of the Corporation. As long as the Presbytery is incorporated under the laws of the State of Indiana, there shall be three directors (trustees) at all times.

## Section 5: Meetings

A.  Stated Meetings

    The time and place of each Stated Meeting shall be determined by Presbytery at the preceding Stated Meeting, or, should Presbytery fail to make this decision, by the Moderator, with approval of the Administrative Committee. The normal times of Stated Meetings shall be as follows:

    * WINTER STATED MEETING: First Thursday in February ( *beginning 2024* )
    * SPRING/SUMMER STATED MEETING: First Thursday in June
    * FALL STATED MEETING: First Friday in October

    Whenever possible, the Stated meetings will be preceded by Presbytery-wide worship services including celebration of the Lord's Supper at the host church or some other practical location.
B.  Special Called Meeting

    Special called meetings of presbytery will only be held when timing necessitates decisions prior to the next stated meeting. Such meetings will be called in strict accordance with the *Book of Church Order*.
C.  Quorum

    Any three (3) Ministers belonging to the Presbytery, together with at least three (3) Ruling Elders, representing at least three (3) churches, being met at the time and place appointed, shall be a quorum competent to proceed to business ( [*BCO* 15.5](https://bco.evangelpresbytery.com/form-of-government.html#the-presbytery)). At any time that attendance at a meeting should fall below the level required for a quorum, the only business which may be conducted is a motion to adjourn the meeting.
D.  Docket

    The normal docket for Stated Meetings shall be as follows:
    
    1. Period of worship and/or prayer
    2. Roll call and letters of excuse
    3. Introduction and seating of corresponding members and visiting brethren
    4. Representative of the Host Church
    5. Minutes of previous meetings
    6. Election of Moderator (when necessary)
    7. Election of other officers (when necessary)
    8. Election of Moderator-in-Nomination (when necessary)
    9. Adoption of the Docket
    10. Reading and assignment of communications
    11. Appointment of Temporary Committees
    12. Appointment of Commissions and/or Ad Interim Committees
    13. Reports of Permanent Committees, with the report of Candidates and Credentials Committee always being first, the other permanent committees rotating their order of report from meeting to meeting.
    14. Unfinished (old) business
    15. Reports from Standing Committees
    16. Reports from officers (Clerk, Treasurer, Trustees)
    17. New Business
    18. Time and place of next Stated Meeting
    19. Adjournment with prayer

    Only those items of business which reach the hands of the Stated Clerk no later than seven (7) days prior to a Stated Meeting may be included in the docket any place other than New Business. This includes reports of Permanent Committees.

    The approved minutes of Evangel Presbytery are a public record. A copy will be provided to anyone who asks for one with the exception of executive session minutes.
E.  Attendance

    Unless honorably retired or declared infirm, all Ministers are expected to attend all meetings of Presbytery. Permission for absences shall be requested through the Stated Clerk or from the floor during the Stated Clerk's report.

## Section 6: Permanent Committees

A.  Membership on Committees

    Eligibility for membership on Permanent Committees of the Presbytery will be the same as for officers of the Presbytery. No man may serve as chairman of more than one permanent committee at any given time. No man may serve as chairman of more than two subcommittees or combination of committee/subcommittee at any given time.
B.  Election and Tenure

    Elections for Chairman of Committees and Subcommittees, as put forward by the Nominations Committee, shall normally be held at the Spring/Summer Stated Meeting. Terms will be for one (1) year. A man may serve as Chairman of a Committee or Subcommittee for three (3) consecutive years. If nominated to continue on the same Committee/Subcommittee after three (3) years, an election by two-thirds (2/3) of the votes cast is required.
C.  Committee Structure

    Each Permanent Committee will be made up of its chairman, and the chairman of each of the assigned Subcommittees serving as members of the main committee. Membership on Subcommittees does not need the approval of the Presbytery as a whole, but will be left to the nomination of the Chairman of the appropriate Subcommittee, with approval of the entire Committee. Membership on Subcommittees may vary at any time according to current needs, with the only restriction being that the same man may not serve more than three (3) continuous years on any given Subcommittee, without approval of two-thirds (2/3) of the votes cast at the time nominated to so continue.
D.  Permanent Committee Descriptions
    1. Administrative Committee
    
        This Committee shall handle all matters which do not normally fall under the oversight of any other Permanent Committee, and will include, but not be limited to, such things as: oversight of the work of the Stated Clerk and Treasurer; interchurch relations; judicial business; insurance and annuities; publicity and general information concerning the work of the Presbytery; stewardship and budget matters. The regular Subcommittees of the Committee, when needed, shall be as follows:
        
        a. Subcommittee on Insurance and Annuities
        b. Subcommittee on Information and Nominations
        c. Subcommittee on Stewardship and Budget
        d. Subcommittee on Judicial Business

        The Administrative Committee through its Subcommittee on Stewardship and Budget shall present to Presbytery at each Fall Stated Meeting a proposed budget for the following calendar year for formal adoption by the Presbytery. The budget may be amended after formal adoption by the Presbytery but as a condition precedent to such amendment, a committee must submit the proposed amendment to the Chairman of the Administrative Committee at least twenty-eight (28) calendar days prior to the time fixed for a Stated Meeting for necessary committee action. A written report outlining the proposed amendment and including said concurrence or non-concurrence of the Administrative Committee shall be submitted by the proposing committee to the Stated Clerk of the Presbytery at least fourteen (14) days before the time fixed for such Stated Meeting in order that the written report and recommendation may be included in the docket for action by the Presbytery.

        Presbytery grants the Administrative Committee the power of a commission to find a complaint in order and to hear the complaint in accordance with [*BCO* 46.8](https://bco.evangelpresbytery.com/the-rules-of-discipline.html#complaints) provided both the party complaining and the party complained against are agreeable to this.

    2. Committee on Church Planting and Domestic Missions

        This Committee shall handle all matters involving church planting and growth within the bounds of the Presbytery, both for particular churches, newly planted churches, and separate missions dealing with residents of the area. Specifically, the Committee shall be responsible for the following:
        
        a. developing and coordinating a strategic plan for church planting within the Presbytery;
        b. preparing calls to evangelists/organizing pastors to develop new churches (which must finally be approved by a majority vote of the presbytery);
        c. coordinating joint efforts with specific churches seeking to plant churches;
        d. providing supervision for mission churches and guiding them through the process to particularization. To aid in this process, the Church Planting Committee has the power of a commission to appoint men to serve on the temporary sessions of mission churches;
        e. recruiting and identifying potential church planters for our Presbytery;
        f. developing and coordinating programs for use by the Church in the areas of Evangelism and Church Growth;
        g. providing aid and assistance to established particular churches having need;

    3. Committee on Foreign Missions

        This Committee shall handle all matters pertaining to information and programs involving the sending of missionary personnel from within the bounds of Presbytery to serve outside the United States. The regular Subcommittee of the Committee, when needed, shall be as follows:

        a. Subcommittee on Recruiting and Support
        b. Subcommittee on Information and Programs

    4. Committee on Candidates and Credentials

        This Committee shall handle all matters pertaining to the care of candidates for the ministry, theological examination of men applying for ordination to the Gospel Ministry; theological examination of views of ministers transferring into the Presbytery; examination of calls issued to ministers within the Presbytery; and other such matters as may involve the credentials of members of Presbytery. The regular Subcommittees of the Committee, when needed, shall be as follows:

        a. Subcommittee on Men Under Care (including Licentiates)
        b. Subcommittee on Theological Examination
        c. Subcommittee on Credentials

        Ordained ministers coming from outside the Presbytery: They ordinarily may not move on to the field without the permission of Presbytery. The Candidates & Credentials Committee has the power of a commission to grant exceptions to this rule but only after having examined a man on his views in committee and only by a majority of the votes cast in a properly called committee meeting with a quorum present. Any who move onto the field under this provision must understand that their examination must still be sustained by Presbytery and their call must still be approved by Presbytery.

        Candidates licensed to preach in Evangel Presbytery: The Committee may act as a commission to grant permission to a current licentiate in Evangel Presbytery to move on to the field and to function as a student supply or stated supply until the next Stated Meeting of Presbytery. The Committee may do this only by a majority of the votes cast in a properly called committee meeting with a quorum present. Any who move onto the field under this provision must understand that their examination must still be sustained by Presbytery and their call must still be approved by Presbytery.

    5. Shepherding Committee

        The Shepherding Committee shall be composed of at least three Ministers and three Elders. The Stated Clerk and Moderator shall serve as ex-officio members. This committee shall meet as often as necessary to fulfill its responsibilities and its duties shall be:
        a. To advise and communicate with Ministers in their relation to sessions and congregations they serve, condemn erroneous opinions which injure the local Church, and visit Churches for the purpose of inquiring into and redressing the evils that may have arisen in them.
        b. To encourage Ministers in their devotion and diligence in their sacred calling and to present to the Presbytery for approval recommendations regarding, censure, dismissal, removal, and judgment of delinquent ministers.
        c. To counsel with sessions of churches without pastors providing the Session and/or Pulpit Nominating Committee assistance in the securing of a pastor, as requested; also to assist in the work of dissolving churches peacefully; and to offer assistance in securing pastors only at the request of the session or local nominating committee, and assist in efforts to dissolve churches peacefully.
        d. To counsel ministers without pastoral charges and to offer assistance in securing pastoral charges for them.
        e. To offer general oversight of ministers, missionaries, chaplains, and evangelists with or without charge and/or laboring inside or outside the bounds of Presbytery.
        f. To maintain alert oversight of retired or incapacitated ministers of Evangel Presbytery, and widows and orphans of ministers; and to represent the ministers, their widows, and orphans in their needs before Presbytery committees.
        g. To act as a commission only to dissolve pastoral relations when both parties concur in the request and, when appropriate in an instance of dissolution, to grant transfer of membership to another ecclesiastical body or presbyteries.
        h. To counsel with Sessions at their request in such matters as are presented by them.
        i. To perform other duties which Presbytery shall deem wise.
        j. To report to Presbytery whenever necessary or when requested by Presbytery.
        k. To maintain a list of Licentiates, Candidates, and Ministers who are available for pulpit supply.

    6. Sessional Records Committee
    
        The Sessional Records Committee shall review the minutes of church Sessions for conformity to the Constitution of Evangel Presbytery.
        
        As directed by presbytery's Stated Clerk, each church Session is to deliver a copy of its court records to the Sessional Record Committee for their examination. . All efforts should be made to see that no more than one-third of the total roll of churches in Presbytery be examined at each Stated Meeting.
        
        Each church Session whose records are scheduled for examination shall email a copy of their unexamined records to the Chairman of the Sessional Records Committee no later than six (6) weeks prior to the upcoming Stated Meeting.
        
        The Sessional Records Committee shall examine the records in accordance with [*BCO* Chapter 43](https://bco.evangelpresbytery.com/the-rules-of-discipline.html#general-review-and-control) and shall classify exceptions as notations, exceptions of form, or exceptions of substance. Notations are typographical errors, misspellings, improper punctuation, and other minor variations in form and clarity. Exceptions of Form are violations of Evangel Presbytery’s Guidelines for Keeping Session Minutes (appendix) or violations of rules of order. Exceptions of Substance are apparent violations of the Scripture or serious irregularities from the Constitution of Evangel Presbytery, actions out of accord with the deliverances of the Presbytery, and matters of impropriety and important delinquencies. Exceptions of Substance should be limited to serious irregularities, gross errors, corrupt practices and heretical opinions.
        
        Notations and exceptions of form shall normally be sent to the Clerk of Session by the Committee without being read before Presbytery or recorded in its minutes. Exceptions of substance shall be reported to Presbytery as recommendations to be voted upon. The Sessional Records shall be approved without exception; or with exception of form and/or substance.
        
        Sessions shall advise the Presbytery by the following Stated Meeting through the Sessional Records Committee that they have disposed of the exception of substance in one of the following manners: the Session agrees with the exception of substance, corrects its record or action if possible, and promises to try to be more careful in the future; or, the Session respectfully disagrees with the exception of substance, states its grounds and refers the exception back to the Presbytery for action. The Sessional Records Committee will bring a recommendation to Presbytery regarding whether or not the disposition of the matter should be considered satisfactory.
        
        The Sessional Records Committee shall report to Presbytery regarding any Sessional Records that have not been submitted for review in the past year.
        
        The Sessional Records Committee shall provide help for any Clerk of Session seeking guidance in preparing Sessional Records for the yearly Presbytery review.
        
    7. Nominating Committee
    
        The Nominating Committee shall be composed of six (6) members with parity of Ministers and Elders. The Moderator shall be an *ex officio* member of the Nominating Committee. Members shall be elected by Presbytery at the Spring/Summer Stated Meeting of Presbytery upon nomination from the floor, with terms of office to begin immediately upon election. One Minister and two Elders shall be elected on odd numbered years, and two Ministers and one Elder shall be elected on even numbered years. The quorum shall be at least one half of the elected members. The Committee shall report to Presbytery at the Spring/Summer Stated Meeting by submitting nominations for all Presbytery committees and other vacancies and shall report at other meetings as vacancies occur. The Committee shall submit its nominations to the Stated Clerk two (2) weeks prior to the Spring/Summer Stated Meeting of Presbytery.

## Section 7: Temporary Committees

The following Temporary Committees shall be appointed by the Moderator for each separate meeting of Presbytery, when required:

A.  Program Committee

    This Committee shall consist of the Moderator, Moderator-in-Nomination, Stated Clerk, and two representatives of the Host Church. This Committee shall meet in advance of the Presbytery and prepare the proposed docket and handle any logistical planning required for the meeting.
    
B.  Overtures Committee

    This Committee shall consist of two Ministers and two Elders, with power to vote at a given meeting of Presbytery, none of whom may also be serving at that time as an officer of Presbytery (other than Trustee), or the Chairman of a Permanent Committee. This Committee will handle and report back all matters assigned to it by the Presbytery for that meeting only.

C.  Resolutions

    This Committee shall consist of one Minister and one Elder, with power to vote at a given meeting of Presbytery, none of whom may also be serving at that time as an officer of Presbytery (other than Trustee) or the Chairman of a Permanent Committee. This Committee will handle the drafting of any resolutions that may be appropriate for that given meeting, including resolutions of thanks and any other such resolutions on which the Presbytery desires to speak.

## Section 8: Ad-Interim Committees and Commissions

The Presbytery may establish Ad-Interim Committees and Commissions to deal with matters before it at any time, with the following limitations:

A.  Each Ad-Interim Committee or Commission will consist of a quorum of a minimum of two Ministers and two Elders, with any larger number always being an equal number of each.
B.  No Ad-Interim Committee or Commission may continue past the next Stated Meeting of Presbytery unless authorized to do so by a majority vote of Presbytery.
C.  No Ad-Interim Committee or Commission may continue for more than two (2) years in any case.
D.  Each Ad-Interim Committee will be appointed by the Moderator.
E.  Each Commission shall be elected by Presbytery.

## Section 9: General Committee Regulations

A.  Speakers

    A committee chairman planning to have a speaker in connection with the presentation of his report at a meeting of Presbytery shall notify the Administrative Committee as far in advance as possible, and in no case later than two (2) weeks prior to the meeting of the Administrative Committee, for inclusion on the docket and the speaker’s appearance before Presbytery.

B.  Written Reports

    All committee reports shall be in written form with sufficient copies for all presbyters in attendance at the meeting of Presbytery. All committees shall meet and prepare the reports prior to the time of presentation to Presbytery. These reports shall be in the hands of the Stated Clerk and the Administrative Committee at least two (2) weeks prior to the meeting of Presbytery. Prayer for the work of the committees will be included in the opening prayer time. Each committee report, therefore, need not be opened with prayer. Nothing contained herein, however, would prohibit prayer for a specific item or need. Each retiring chairman of a committee shall transmit all files, records and reports pertaining to the committee to the incoming committee chairman. In the event of the disestablishment of a committee, all such records shall be placed in the hands of the Stated Clerk.

C.  Activities

    All committees shall hold duly constituted meetings at least once a year and report at least annually to Presbytery. If any committee believes that its activities are not contributing to the work of the Presbytery, it shall recommend its dissolution to Presbytery. If no meeting is held by a committee during the year, the Administrative Committee shall consider what shall be done about the designated tasks assigned to that committee, and report to the next meeting of Presbytery. Committees ought not to schedule meetings concurrent with main presbytery meetings. The quorum for any committee meeting shall be two Ministers and two Elders unless otherwise stated.

D.  Subcommittees

    Committees, when it is expedient, shall be empowered to create such subcommittees as are deemed necessary by them. Such subcommittees shall report to Presbytery through the parent committee. They shall not be disestablished without the knowledge of Presbytery. The composition of such subcommittees shall be carried into the minutes of Presbytery together with the terms of office of their members. The Bylaws requirements for committee membership shall apply to subcommittees.

E.  Membership

    Only in extraordinary cases shall the membership of a committee include more than two representatives from the same particular church. Membership on all committees shall be as designated in the Manual. Terms of membership shall expire at the close of the Winter meeting of Presbytery. Filling an unexpired term is not to be counted as a term. All committees shall be arranged in classes so that not more than one-third (1/3) shall retire at any one time, except committees with fewer than six (6) members.

## Section 10: Electronic Meetings

Sometimes matters arise needing action prior to the next stated meeting of presbytery. When a special called meeting of presbytery or one of its committees, subcommittees, or commissions is impractical, special called meetings are allowed via any means of communication which allows all participants simultaneously to hear and communicate with each other (for example, tele-conference or video-conference). If a meeting is conducted by such means, the presiding officer shall inform all participants at the commencement of the meeting that a meeting is taking place at which official business may be transacted. Any participant in a meeting by such means shall be deemed present in person at such meeting. The moderator of the meeting may establish reasonable rules to conduct the meeting. Committees and subcommittees may hold their regular stated meetings in this manner, also.

Written consent by the members of the Presbytery, a committee, or a subcommittee can be undertaken via email, or other electronic record communication, if the written consent setting forth the action to be taken is circulated to all members via email, or other electronic record communication, and at least eighty percent (80%) of the members indicate their approval by return email or other approved electronic record communication. The Presbytery shall confirm with each member the electronic address or addresses, such as an email address or text message number, for that member to be used for purposes of sending and receiving email, text or other electronic record communications, and for the purpose of notices to and from the Presbytery, and shall maintain such information as part of the Presbytery’s current records, which may be maintained electronically. The Presbytery shall provide its address, and the electronic addresses of the other members, to be used for purposes of taking such action. The Presbytery may provide for any particular requirements, method or means for taking action electronically and for notices to and from the Presbytery and its members, in which case the action to be taken shall be taken in accordance with such requirements, method, or means.

## Section 11: Parliamentary Authority

All parliamentary procedures must be in accordance with the *Book of Church Order* and the most recent edition of *Robert’s Rules of Order* . The Moderator may appoint a member of Presbytery to assist him in these matters, who will serve as Parliamentarian only for the term of the actual meeting.

## Section 12: Suspension and Amendment of Bylaws

These Bylaws may be temporarily suspended, amended, or revised at any Stated Meeting of Presbytery by a two-thirds (2/3) majority of the votes cast, unless such suspension, amendment, or revision would violate any part of the *Book of Church Order* . Any permanent amendment, revision, or repeal of the Bylaws must be proposed in writing at a Stated Meeting, approved by a two-thirds (2/3) majority of the votes cast of that Stated Meeting, and ratified by a two-thirds (2/3) majority of the votes cast at the following Stated Meeting of Presbytery.

## Appendix 1: Guidelines for Keeping Sessional Records

A.  Formatting Guidelines

    All minutes should be typed. They should be simple in word and in formatting. When submitting minutes for review by the Sessional Records Committee, all minutes from all meetings (session, congregational, etc.) should be included in one PDF document in chronological order with pages numbered consecutively, leaving no blank pages between meetings and no records left out. As with all important digital documents, great care should be taken to ensure that Session minute archives have both local and remote backups. Sessions may keep a physical hard copy of their minutes in addition to their digital copy. If they choose to do so, however, they must ensure that the physical archives do not conflict with the digital ones. The annual budget and annual statistical report should be submitted to the Sessional Records as separate PDF files.
    
B.  Session Minutes must include the following:

    1. A statement of the date, time, place, and purpose of the meeting (stated (i.e., regular scheduled), called, special called, etc.)
    2. The portion of a call that indicates the purpose of any called meeting.
    3. That the meeting was opened and closed with prayer.
    4. The names of all in attendance or absent from the meeting.
    5. That a quorum was present for the meeting.
    6. Communications received, and any action taken because of the communications.
    7. Adoption of the minutes from previous meeting(s).
    8. A statement that indicates the receiving of the Treasurer’s report (a.k.a financial report) as information.
    9. The actions of the Session including all the motions adopted and business transacted.


C.  When applicable, the minutes shall include the following:
    1. A record of all baptisms and dates of the celebration of the Lord’s Supper.
    2. Election of commissioners to presbytery.
    3. A record of the call and purpose for each congregational or corporation meeting.
    4. A motion calling for the nomination and election of church officers.
    5. A record of the officers nominated, trained and examined by the Session.
    6. A statement that indicates the review and approval of the Deacons' minutes.
    7. A statement in the December or the following January minutes that records annual housing allowance(s) approved by the Session for pastoral staff.
    8. "A fair record of baptisms, of those admitted to the Lord’s table, of non-communing members, and of the births, marriages, deaths, and dismissions of church members and of any baptisms and marriage ceremonies presided over by the pastors of the church outside its bounds" ([*BCO* 14.8](https://bco.evangelpresbytery.com/form-of-government.html#the-church-session)).
    9. A copy of the approved operating budget and the yearly statistical report should be attached to the minutes once per year.

D.  The following additional records should be kept and submitted once per year:

    1. An annual statistical report which contains “...a fair record of baptisms, of those admitted to the Lord’s table, of non-communing members, and of the births, marriages, deaths, and dismissions of church members and of any baptisms and marriage ceremonies presided over by the pastors of the church outside its bounds” ([BCO 14.8](https://bco.evangelpresbytery.com/form-of-government.html#the-church-session)).
    2. A copy of the approved operating budget.

## Appendix 2: Evangel Presbytery Bylaws Revision Form

*Please copy and paste the following form into an email or document and send the completed form to the Stated Clerk of Evangel Presbytery (clerk@evangelpresbytery.com) at least one month in advance of a stated meeting for consideration at that meeting.*

Your name:

Your church:

Are you a **pastor** or an **elder**?

**Suggested change to bylaws:**

Is this a **revision**, **addition** or **removal**?

Address of change: *(for example, “Section 8, B”)*

Please write out the suggested amendment: 

Please present rationale and Scripture references for the suggested amendment: 

Are there others who share your view? Please list them below. *(Please include each man's **name**, **church** and **church office**.)*