# Officers

All officers shall be elected by a majority of the votes cast at the Stated Meeting scheduled for that purpose. The various offices of the Presbytery, and their functions, are as follows:

A. Moderator

  1. Eligibility: The Moderator shall be a Pastor who is a member in good standing of the Presbytery, or an Elder in good standing of a member church of the Presbytery. The Elder does not have to be currently active on the Session of his church if that church follows a rotation system for its Session. A moderator may not succeed himself, nor serve a second term in office within one year of previously having served.
  2. Tenure: The Moderator of the Presbytery shall be chosen at each stated meeting or for a period of time up to one (1) year (BCO 12.3). He will continue to serve in office until a successor is elected at a Stated Meeting. He will preside over called or other special meetings, and otherwise function as Moderator during his tenure. As a general rule, the position of Moderator should alternate between Pastors and Elders.
  3. Moderator-in-Nomination: At each Stated Meeting of Presbytery or at the Stated Meeting preceding the final meeting of the current Moderator’s tenure, a Moderator-in-Nomination will be elected, with the understanding that his name will automatically be placed in nomination for the office of moderator at the next Stated Meeting. This policy is established to enable men to prepare themselves to function in this office to the best of their ability, and to be aware of current issues before the court. However, election as Moderator-in-Nomination does not require the Presbytery to elect this nominee at its next Stated Meeting, at which time a normal process of nominations and elections will be followed.
  4. Duties:
    a. The Moderator of Presbytery will function as chairman of all meetings of Presbytery, following approved parliamentary procedure.
    b. If no worship service has been held prior to the meeting of Presbytery, the retiring Moderator shall ordinarily bring a message from God's Word in an appropriate time of devotion.
    c. Between meetings, the Moderator has the responsibility to speak for the Presbytery in matters in which the Presbytery itself has made its commitments clear, and he should be consulted in all matters affecting the Presbytery as a whole.
    d. He may appoint a Parliamentarian to serve for each Stated Meeting.
    e. In any emergency the Moderator may, by adequate and appropriate means, including circular letter, telephone notification, or email, change the time or place (or both) of meetings to which the court stands adjourned, giving reasonable notice of such change.
    f. The Moderator shall nominate the members of Temporary Committees and Ad Interim Committees. Nominees will be approved by the Presbytery. The Moderator shall appoint the chairmen of Temporary Committees and Ad Interim Committees and inform the Presbytery of his appointment. He may also advise the members of these committees to elect chairmen from among themselves.
    g. The Moderator, by the authority vested in him, is an ex-officio member of the Administrative Committee.

---------------

Haven't really tried the formatting after this point.

B. Vice Moderator
The Vice Moderator shall be the immediate past Moderator and shall serve at the request of the Moderator, or when the Moderator is unable to serve. In the event the Vice Moderator is not able to serve, the Stated Clerk shall preside, and, as its first order of business, Presbytery shall nominate and elect a Moderator Pro Tem to moderate during the Moderator’s and Vice Moderator’s absence. The Vice Moderator, by the authority vested in him, is an ex-officio member of the Administrative Committee
C. Stated Clerk
1. Eligibility: The Stated Clerk shall be a Pastor who is a member in good standing of the Presbytery, or an Elder in good standing of a member church of the Presbytery. The Elder does not have to be currently active on the Session of his church if that church follows a rotation system for its Session.
2. Tenure: The Stated Clerk will be elected at the Spring/Summer Stated Meeting and shall serve for a period of three (3) years. He may succeed himself as often as the Presbytery so desires. It is deemed advisable that this be done whenever possible.
3. Duties: The Stated Clerk shall perform the duties assigned by the Book of Church Order (12.4). He shall perform other duties as assigned by the Presbytery. The Stated Clerk may receive an annual stipend to be fixed by the Presbytery. In the administration of his duties, the Stated Clerk shall be under the supervision of the Administrative Committee. The Presbytery shall provide or reimburse the Stated Clerk for all costs required by the duties of his office upon presentation of proper cost statements subject to the limitations of the current approved budget. His duties will include, but not be limited to the following,
keep proper minutes of all Presbytery and Committee/Commission meetings, giving certified extracts therefrom when required;
assemble the items of business to come before the Presbytery and refer each item to the proper committee (if the clerk has questions regarding reference, he is to consult with the Administrative Committee before making reference);
send to each member and church (including men under care) notice of all meetings; note the attendance at each meeting and make recommendations concerning absences at Stated Meetings;
maintain permanent, orderly records of all Presbytery correspondence and other matters;
notify each Committee and Commission chairman of his appointment, membership and business before it;
maintain a supply of necessary forms for use by churches;
make all communications authorized by Presbytery;
open meetings of Presbytery when the Moderator is unable to do so, and serve until a new Moderator is elected;
advise the Moderator in every possible way, by keeping him informed of matters requiring his attention, giving notice for him of Called Meetings of Presbytery or changes in time and place of Meetings, making the facilities of the office available to him for correspondence or other matters, and rendering any service requested by the Moderator in connection with the operation of Presbytery.
He shall be an ex-officio member of Presbytery's Administrative Committee.
4. Assistant Clerks and Office Staff. When necessary to the performance of his duties, and upon recommendation by the Administrative Committee, the Presbytery may authorize the hiring of clerical help and services (such as printing and duplication) to assist the Stated Clerk in carrying out the duties of his office.
D. Recording Clerk
The Recording Clerk shall be appointed by the Stated Clerk for a term of one (1) year, informing the Presbytery of this appointment during his clerk’s report at the beginning of the first presbytery meeting following that appointment. The Recording Clerk shall normally be a member of Presbytery or a ruling elder of a member church. Election shall normally be held at the Spring/Summer Stated Meeting, with term of office to begin at the Fall Stated Meeting. The Recording Clerk may receive an annual stipend to be fixed by the Presbytery. He shall be given two (2) copies of all committee reports as presented to Presbytery for inclusion in the Minutes and a written copy of all motions adopted by Presbytery. As soon as practicable, he shall convey the Minutes in type-written form (or any other form acceptable to the Stated Clerk), properly recorded, to the Stated Clerk for editing and publishing. The Minutes shall be reviewed by the Stated Clerk and Moderator prior to circulation to the presbytery for their review and approval.
E. Treasurer
1. Eligibility: Eligibility for the office of Treasurer shall be the same as for the office of Stated Clerk. The Stated Clerk may also serve as Treasurer.
2. Tenure: Tenure for the office of Treasurer shall be the same as for the office of Stated Clerk.
3. Duties: The Treasurer shall perform those duties required of him by the Book of Church Order and those other duties as may be assigned by the Presbytery. In the performance of his duties, the Treasurer shall come under the oversight of the Administrative Committee. The Presbytery shall provide or reimburse the Treasurer for all costs required by the duties of his office upon presentation of proper cost statements subject to the limitations of the current approved budget. He shall be bonded in an amount to be determined by the Presbytery, or the books of the presbytery shall be audited, annually. His duties shall include but not be limited to:
custody of the funds and securities belonging to the Presbytery, and not otherwise designated;
receive, deposit, and disburse such funds as directed by the Presbytery;
keep an accurate account of the finances of the Presbytery, not only of those funds in the custody, but also by means of quarterly reports from other committees handling separate funds;
prepare or have prepared reports of the financial condition of the Presbytery at each stated meeting;
in general, perform all of the duties incident to the office of Treasurer.
F. Trustees
1. Eligibility: The Board of Trustees of the Presbytery shall consist of the Stated Clerk, plus two other members of Presbytery elected at large. Eligibility for this office shall be the same as for all other offices.
2. Tenure: Trustees will serve for the period of their Committee Chairmanship, or three (3) years, whichever is shorter. Trustees may be re-elected to office upon two-thirds (2/3)of the votes cast. Election will be held at Spring/Summer Stated Meeting.
3. Duties: The Trustees shall receive and hold for use of Presbytery all real and personal property, grants, endowments, and such other funds acquired, devised, purchased, or donated, not otherwise disposed of. They shall be the legal Officers of the Corporation. As long as the Presbytery is incorporated under the laws of the State of Indiana, there shall be three directors (trustees) at all times.