# Electronic Meetings

Sometimes matters arise needing action prior to the next stated meeting of presbytery. When a special called meeting of presbytery or one of its committees, subcommittees, or commissions is impractical, special called meetings are allowed via any means of communication which allows all participants simultaneously to hear and communicate with each other (for example, tele-conference or video-conference). If a meeting is conducted by such means, the presiding officer shall inform all participants at the commencement of the meeting that a meeting is taking place at which official business may be transacted. Any participant in a meeting by such means shall be deemed present in person at such meeting. The moderator of the meeting may establish reasonable rules to conduct the meeting. Committees and subcommittees may hold their regular stated meetings in this manner, also.

Written consent by the members of the Presbytery, a committee, or a subcommittee can be undertaken via email, or other electronic record communication, if the written consent setting forth the action to be taken is circulated to all members via email, or other electronic record communication, and at least eighty percent (80%) of the members indicate their approval by return email or other approved electronic record communication. The Presbytery shall confirm with each member the electronic address or addresses, such as an email address or text message number, for that member to be used for purposes of sending and receiving email, text or other electronic record communications, and for the purpose of notices to and from the Presbytery, and shall maintain such information as part of the Presbytery’s current records, which may be maintained electronically. The Presbytery shall provide its address, and the electronic addresses of the other members, to be used for purposes of taking such action. The Presbytery may provide for any particular requirements, method or means for taking action electronically and for notices to and from the Presbytery and its members, in which case the action to be taken shall be taken in accordance with such requirements, method, or means.